[Icon Theme]
Name=Lila HD-cursor
Comment=Professional HD Icon Theme for Linux systems (2026 Reboot)
Inherits=Lila_HD,Adwaita,hicolor
Example=folder-visiting

# Directory structure
Directories=apps/scalable,places/scalable,mimetypes/scalable,actions/scalable,categories/scalable,devices/scalable,emblems/scalable,emotes/scalable,status/scalableapps/scalable,places/scalable,mimetypes/scalable,actions/scalable,categories/scalable,devices/scalable,emblems/scalable,emotes/scalable,status/scalable

[apps/scalable]
Size=64
Context=Applications
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[places/scalable]
Size=64
Context=Places
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/scalable]
Size=64
Context=MimeTypes
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[actions/scalable]
Size=64
Context=Actions
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[categories/scalable]
Size=64
Context=Categories
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[devices/scalable]
Size=64
Context=Devices
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[emblems/scalable]
Size=64
Context=Emblems
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[emotes/scalable]
Size=64
Context=Emotes
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512

[status/scalable]
Size=64
Context=Status
TargetSize=256
Type=Scalable
MinSize=16
MaxSize=512
